### ISSUE TITLE
Quickstart for the Solace VMR to be deployed in Google Container Engine

### ISSUE THREAD

**Issue by darrylmacrae** [SolaceProducts/solace-gke-quickstart#1]
This is a requirement to develop a quickstart to deploy the VMR in a Kubernetes cluster in Google Container Engine (GKE).  This is to be implemented and delivered in two phases.  Initially support will be provided for deploying the VMR in a standalone configuration for demos/POCs (Phase 1), subsequently we will provide support for deploying the VMR in a High Availability (HA) cluster configuration for Production deployments (Phase 2).

This issue focuses on Phase 1 of this development effort.

**Comment by KenBarr** [comment]
Phase 1 - Code complete and available for QA.

**Comment by PhilippeKhalife** [comment]
Phase 1 - Delivered in release v0.1.0

**Comment by PhilippeKhalife** [comment]
Release v0.2.0 is done, closing
